http:
  port: 8081
secret:
  value: "campus-app"
smtp:
  host: "smtp.cc.iitk.ac.in"
  port: 25
redis:
  host: "localhost"
  port: 6379
postgres:
  username: "subho"
  host: "localhost"
  port: 26257
  dbname: "web_app"
